#!/bin/bash

files=""
for dir in writeups/*/
do
        for file in $dir*
        do
                file=${file/writeups\//}
                file="[$file](https://github.com/guysudai1/writeups/writeups/$file)"
                files="${files}, $file"
        done
        files="${files/, /}"
done

message="Hey, my name is guysudai1 and this is a repo for CTFs I solved.\nCurrent available writeups: $files" 

message+="\n\nTree: \n\n"
message+=$(tree writeups/)

echo -e "$message"
